import { chromium } from "playwright-core";
import { existsSync } from "node:fs";
import { mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

const baseURL = process.env.HORTALAB_URL || "http://127.0.0.1:4173";
const candidates = [process.env.CHROME_PATH, "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe", "/usr/bin/google-chrome", "/usr/bin/chromium"].filter(Boolean);
const executablePath = candidates.find(existsSync);
if (!executablePath) throw new Error("Nenhum Chromium instalado foi encontrado.");

const qaDir = join(tmpdir(), "hortalab-escola-qa");
await mkdir(qaDir, { recursive: true });
const browser = await chromium.launch({ headless: true, executablePath });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, locale: "pt-BR", acceptDownloads: true });
const page = await context.newPage();
const errors = [];
const warnings = [];
const externalRequests = [];
page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); if (message.type() === "warning") warnings.push(message.text()); });
page.on("pageerror", (error) => errors.push(error.message));
page.on("request", (request) => { const url = new URL(request.url()); if (!["127.0.0.1", "localhost"].includes(url.hostname) && !["data:", "blob:"].includes(url.protocol)) externalRequests.push(request.url()); });
page.on("dialog", (dialog) => dialog.accept());
const check = (condition, message) => { if (!condition) throw new Error(message); };
const text = async (selector) => (await page.locator(selector).textContent()) || "";
const expectText = async (selector, expected) => { await page.waitForFunction(({ selector, expected }) => document.querySelector(selector)?.textContent.includes(expected), { selector, expected }); check((await text(selector)).includes(expected), `Esperava "${expected}" em ${selector}.`); };

await page.goto(`${baseURL}/index.html`, { waitUntil: "networkidle" });
await page.evaluate(() => new Promise((resolve) => { const request = indexedDB.deleteDatabase("hortalab-escola-device"); request.onsuccess = request.onerror = request.onblocked = () => resolve(); }));
await page.reload({ waitUntil: "networkidle" });
check((await page.title()).includes("planeje a horta da escola"), "A entrada oficial não carregou.");
check(await page.locator("#v2Essentials").isVisible(), "A etapa essencial não está visível.");
await expectText("#v2StorageStatus", "Plano salvo aqui");
check(await page.locator('[data-v2-step="7"]').isDisabled(), "Uma etapa futura deveria permanecer bloqueada até ser alcançada.");
const visibleEntryText = await page.locator("body").innerText();
for (const term of ["SQLite", "JSON", "layout isométrico", "painel ESG", "banco de dados"]) check(!visibleEntryText.toLowerCase().includes(term.toLowerCase()), `Termo técnico exposto na entrada: ${term}.`);
await page.locator("#v2-step-1-title").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "journey-start-desktop.png"), fullPage: false });
await page.locator(".skip-link").focus();
const firstKeyboardFocus = await page.evaluate(() => {
  const active = document.activeElement;
  const style = getComputedStyle(active);
  const firstFocusable = document.querySelector('a[href], button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])');
  return { className: active?.className || "", firstClassName: firstFocusable?.className || "", outlineStyle: style.outlineStyle, outlineWidth: style.outlineWidth };
});
check(String(firstKeyboardFocus.className).includes("skip-link"), "O primeiro foco do teclado não chegou ao link de pular conteúdo.");
check(String(firstKeyboardFocus.firstClassName).includes("skip-link"), "O link de pular conteúdo não é o primeiro controle da página.");
check(firstKeyboardFocus.outlineStyle !== "none" && firstKeyboardFocus.outlineWidth !== "0px", "O foco do teclado não está visível.");

await page.locator("[data-v2-next]").first().click();
await page.locator('[data-v2-scenario="expanded"]').click();
await page.locator('[data-v2-panel="2"] [data-v2-next]').click();
check((await text("#v2CompositionArea")).includes("50,0 de 50,0"), "O cenário de 50 m² não totaliza 50 m².");
check(await page.locator("#v2PlotGrid .v2-plot-item").count() === 11, "A composição expandida deveria ter 11 zonas.");
const firstCompositionId = await page.locator("#v2PlotGrid .v2-plot-item").first().getAttribute("data-v2-component-id");
await page.locator("#v2PlotGrid [data-v2-select]").first().click();
check(await page.locator("#v2ComponentEditor").isVisible(), "O editor da zona selecionada não abriu.");
await page.locator('[data-v2-add="signage"]').click();
check((await text("#v2Live")).includes("Não há área livre"), "A composição cheia deveria explicar por que não aceita outro componente.");
check(await page.locator("#v2PlotGrid .v2-plot-item").count() === 11, "Um componente impossível foi adicionado ao cenário cheio.");
await page.locator("#v2CompositionAreaInput").fill("100");
await page.locator("#v2CompositionAreaInput").press("Tab");
check((await text("#v2CompositionArea")).includes("50,0 de 50,0"), "A edição de área permitiu ultrapassar o cenário.");
await page.locator('[data-v2-move="1"]').click();
check((await page.locator("#v2PlotGrid .v2-plot-item").first().getAttribute("data-v2-component-id")) !== firstCompositionId, "O controle acessível não reordenou a composição.");
await page.locator('[data-v2-history="undo"]').click();
check((await page.locator("#v2PlotGrid .v2-plot-item").first().getAttribute("data-v2-component-id")) === firstCompositionId, "Desfazer não restaurou a ordem anterior.");
await page.locator('[data-v2-plot-view="list"]').click();
check(await page.locator("#v2PlotGrid").getAttribute("data-view") === "list", "A visualização em lista não foi ativada.");
await page.locator('[data-v2-plot-view="map"]').click();
await page.locator("[data-v2-grid-toggle]").click();
check(await page.locator("#v2PlotGrid").evaluate((node) => node.classList.contains("is-grid-hidden")), "O controle de grade não ocultou a grade.");
await page.locator("[data-v2-grid-toggle]").click();
check(!(await page.locator("#v2PlotGrid").evaluate((node) => node.classList.contains("is-grid-hidden"))), "O controle de grade não restaurou a grade.");
await page.locator("#v2PlotGrid .v2-plot-item").first().dragTo(page.locator("#v2PlotGrid .v2-plot-item").nth(2));
check((await page.locator("#v2PlotGrid .v2-plot-item").first().getAttribute("data-v2-component-id")) !== firstCompositionId, "Arrastar não reordenou a composição.");
await page.locator('[data-v2-history="undo"]').click();
check((await page.locator("#v2PlotGrid .v2-plot-item").first().getAttribute("data-v2-component-id")) === firstCompositionId, "Desfazer não restaurou a ordem após arrastar.");
await page.locator("#v2Library").evaluate((node) => { node.scrollTop = 0; });
await page.locator("#v2PlotGrid").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "composition-desktop.png"), fullPage: false });
await page.locator('[data-v2-panel="3"] [data-v2-next]').click();
check(await page.locator("#v2IsoCanvas").isVisible(), "O layout isométrico não está visível.");
check(await page.locator("#v2IsoCanvas .iso-hit").count() === 11, "A cena não renderizou todos os componentes.");
for (const type of ["bed", "paths", "maneuver", "water", "seedlings", "tools", "compost", "pedagogy", "observation"]) {
  const sprite = page.locator(`#v2IsoCanvas [data-iso-type="${type}"] .iso-sprite`).first();
  check(await sprite.count() > 0, `O PNG isométrico de ${type} não foi renderizado.`);
  check((await sprite.getAttribute("href"))?.endsWith(`/${type}.png`), `O PNG isométrico de ${type} tem origem incorreta.`);
}
const waterObject = page.locator('#v2IsoCanvas [data-iso-type="water"]');
const waterSprite = waterObject.locator(".iso-sprite");
const positionInCanvas = (locator) => locator.evaluate((element) => {
  const objectBox = element.getBoundingClientRect();
  const canvasBox = element.closest("svg").getBoundingClientRect();
  return { x: objectBox.x - canvasBox.x, y: objectBox.y - canvasBox.y };
});
const waterSpriteBox = await waterSprite.boundingBox();
check(waterSpriteBox, "O objeto de água não possui uma área visível para clique.");
await page.mouse.click(waterSpriteBox.x + waterSpriteBox.width / 2, waterSpriteBox.y + waterSpriteBox.height / 2);
check(await waterObject.getAttribute("aria-pressed") === "true", "O clique direto no objeto 3D não o selecionou.");
check((await text("#v2SelectedTitle")).includes("Ponto de água"), "A seleção por clique não atualizou os controles.");
check((await text("#v2Live")).includes("Ponto de água selecionado"), "A seleção por clique não atualizou o feedback acessível.");
check(await page.locator('[data-v2-nudge="ArrowLeft"]').isEnabled(), "Os botões de direção não foram ativados após a seleção.");
const waterBefore = await positionInCanvas(waterObject);
await page.locator('[data-v2-nudge="ArrowLeft"]').click();
const waterLeft = await positionInCanvas(waterObject);
check(waterLeft.x < waterBefore.x - 20 && Math.abs(waterLeft.y - waterBefore.y) < 1, "O botão esquerdo não moveu a água visualmente para a esquerda.");
check((await text("#v2Live")).includes("Ponto de água movido para esquerda"), "O movimento pelo botão não atualizou o feedback.");
await page.locator('[data-v2-nudge="ArrowRight"]').click();
const waterReturned = await positionInCanvas(waterObject);
check(waterReturned.x > waterLeft.x + 20 && Math.abs(waterReturned.y - waterLeft.y) < 1, "O botão direito não devolveu a água visualmente para a direita.");
await waterObject.focus();
const keyboardBefore = await positionInCanvas(waterObject);
await waterObject.press("ArrowLeft");
const keyboardLeft = await positionInCanvas(waterObject);
check(keyboardLeft.x < keyboardBefore.x - 20 && Math.abs(keyboardLeft.y - keyboardBefore.y) < 1, "A seta esquerda do teclado não moveu a água.");
await waterObject.press("ArrowRight");
check((await text("#v2ZoomStatus")).includes("100%"), "O tamanho inicial da imagem não foi informado.");
await page.locator("#v2ZoomIn").click();
check((await text("#v2ZoomStatus")).includes("110%"), "O botão de aumentar não atualizou o tamanho da imagem.");
await page.locator("#v2ZoomOut").click();
check((await text("#v2ZoomStatus")).includes("100%"), "O botão de diminuir não restaurou o tamanho da imagem.");
await page.locator("#v2Rotate").click();
check((await text("#v2Live")).includes("Vista girada"), "A rotação não atualizou o feedback.");
const rotatedBefore = await positionInCanvas(waterObject);
await waterObject.press("ArrowLeft");
const rotatedLeft = await positionInCanvas(waterObject);
check(rotatedLeft.x < rotatedBefore.x - 20 && Math.abs(rotatedLeft.y - rotatedBefore.y) < 1, "A seta esquerda ficou invertida depois de girar a vista.");
await waterObject.press("ArrowRight");
const rotatedReturned = await positionInCanvas(waterObject);
check(rotatedReturned.x > rotatedLeft.x + 20 && Math.abs(rotatedReturned.y - rotatedLeft.y) < 1, "A seta direita ficou invertida depois de girar a vista.");

await page.locator('[data-v2-panel="4"] [data-v2-next]').click();
await page.locator("#v2Activities input").first().check();
await page.locator("#v2Activities input").nth(1).check();
await expectText("#v2ActivityHint", "2 atividades escolhidas");
await page.locator("#v2Note").fill("Acompanhar germinação e registrar medidas.");
await page.locator('#v2CarePlan select[name="routine"]').selectOption("fewTimes");
await page.locator('#v2CarePlan select[name="backup"]').selectOption("defined");
await page.locator('#v2CarePlan select[name="costTracking"]').selectOption("yes");
await page.locator('#v2CarePlan select[name="pauseCriteria"]').selectOption("yes");
await page.locator('[data-v2-panel="5"] [data-v2-next]').click();
check(await page.locator('[data-v2-panel="6"]').isVisible(), "A revisão de imprevistos não foi aberta.");
check(await page.locator("#v2Feasibility .v2-indicator").count() === 4, "Os quatro pontos de revisão do plano não foram mostrados.");
await page.locator('#v2EventCard input[value="rotation"]').check();
await expectText("#v2EventCard", "O que essa escolha muda");
await page.locator("#v2EventPicker").selectOption("waterRestriction");
await page.locator('#v2EventCard input[value="adapt"]').check();
await expectText("#v2EventCard", "quantidade realmente disponível");
await page.locator('[data-v2-panel="6"] [data-v2-next]').click();
check(await page.locator("#v2Summary").isVisible(), "O resumo não foi gerado.");
check((await text("#v2Summary")).includes("50 m²"), "O resumo não preservou o cenário.");
check((await text("#v2Summary")).includes("Férias escolares"), "O plano final não registrou o imprevisto de férias.");
check((await text("#v2Summary")).includes("Restrição de água"), "O plano final não registrou o imprevisto de água.");
check((await text("#v2Summary")).includes("Ordem sugerida"), "O plano final não apresentou uma sequência de acompanhamento.");
check((await text("#v2Summary")).includes("Orçamento:"), "O plano final não registrou os recursos informados.");

const jsonDownloadPromise = page.waitForEvent("download");
await page.locator("#v2Export").click();
const jsonDownload = await jsonDownloadPromise;
const jsonPath = join(tmpdir(), "hortalab-plano-e2e.json");
await jsonDownload.saveAs(jsonPath);
const exported = JSON.parse(await readFile(jsonPath, "utf8"));
check(exported.state.scenarioId === "expanded", "O JSON não preservou o cenário.");
check(exported.state.components.reduce((sum, item) => sum + item.area, 0).toFixed(1) === "50.0", "O JSON exportado não totaliza 50 m².");

const sqliteDownloadPromise = page.waitForEvent("download");
await page.locator("#v2ExportSqlite").click();
const sqliteDownload = await sqliteDownloadPromise;
const sqlitePath = join(tmpdir(), "hortalab-escola-e2e.sqlite");
await sqliteDownload.saveAs(sqlitePath);
const sqliteBytes = await readFile(sqlitePath);
check(sqliteBytes.byteLength > 1000, "O backup SQLite parece incompleto.");
check(sqliteBytes.subarray(0, 15).toString("ascii") === "SQLite format 3", "O arquivo exportado não tem cabeçalho SQLite.");

await page.reload({ waitUntil: "networkidle" });
check(await page.locator('[data-v2-panel="7"]').isVisible(), "A etapa atual não foi restaurada pelo armazenamento local.");
await page.locator("#v2ResetBottom").click();
await expectText("#v2StorageStatus", "Plano salvo aqui");
check(await page.locator('[data-v2-panel="1"]').isVisible(), "O reinício não voltou ao início.");
await page.setInputFiles("#v2ImportFile", jsonPath);
await expectText("#v2Live", "A cópia foi aberta");
check(await page.locator('[data-v2-panel="7"]').isVisible(), "A primeira cópia não restaurou o plano final.");
await page.locator("#v2ResetBottom").click();
await expectText("#v2StorageStatus", "Plano salvo aqui");
await page.setInputFiles("#v2ImportFile", sqlitePath);
await expectText("#v2Live", "A cópia foi aberta");
check(await page.locator('[data-v2-panel="7"]').isVisible(), "A cópia completa não restaurou o plano final.");
check((await text("#v2Summary")).includes("50 m²"), "A importação SQLite perdeu o cenário.");

await page.emulateMedia({ media: "print" });
check(await page.locator("#v2Summary").isVisible(), "O resumo não aparece para impressão.");
await page.emulateMedia({ media: "screen" });

for (const width of [360, 768, 1024, 1440]) {
  await page.setViewportSize({ width, height: width === 360 ? 800 : 900 });
  await page.locator('[data-v2-step="4"]').click();
  const metrics = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }));
  check(metrics.scrollWidth <= metrics.clientWidth + 1, `Overflow horizontal em ${width}px: ${metrics.scrollWidth} > ${metrics.clientWidth}`);
  check(await page.locator("#v2IsoCanvas").isVisible(), `Layout isométrico não visível em ${width}px.`);
}

await page.setViewportSize({ width: 1440, height: 900 });
await page.locator("#v2IsoCanvas").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "layout-desktop.png"), fullPage: false });
await page.locator('[data-v2-step="6"]').click();
await page.locator("#v2-step-6-title").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "review-desktop.png"), fullPage: false });
await page.setViewportSize({ width: 360, height: 800 });
await page.locator('[data-v2-step="6"]').click();
await page.locator("#v2-step-6-title").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "review-mobile.png"), fullPage: false });
await page.locator('[data-v2-step="4"]').click();
await page.locator("#v2IsoCanvas").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "layout-mobile.png"), fullPage: false });
await page.locator('[data-v2-step="3"]').click();
await page.locator("#v2PlotGrid").scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "composition-mobile.png"), fullPage: false });

await page.setViewportSize({ width: 1440, height: 900 });
await page.goto(`${baseURL}/cartilha.html`, { waitUntil: "networkidle" });
const manualLink = page.locator('a[download][href="output/pdf/manual-de-uso-hortalab-escola.pdf"]');
check(await manualLink.isVisible(), "O download do manual não está visível na área de ajuda.");
await manualLink.scrollIntoViewIfNeeded();
await page.screenshot({ path: join(qaDir, "manual-download-desktop.png"), fullPage: false });
await page.setViewportSize({ width: 360, height: 800 });
await manualLink.scrollIntoViewIfNeeded();
const guideMetrics = await page.evaluate(() => ({ scrollWidth: document.documentElement.scrollWidth, clientWidth: document.documentElement.clientWidth }));
check(guideMetrics.scrollWidth <= guideMetrics.clientWidth + 1, `Overflow horizontal na ajuda em 360 px: ${guideMetrics.scrollWidth} > ${guideMetrics.clientWidth}`);
await page.screenshot({ path: join(qaDir, "manual-download-mobile.png"), fullPage: false });
const manualDownloadPromise = page.waitForEvent("download");
await manualLink.click();
const manualDownload = await manualDownloadPromise;
const manualPath = join(tmpdir(), "manual-de-uso-hortalab-escola-e2e.pdf");
await manualDownload.saveAs(manualPath);
const manualBytes = await readFile(manualPath);
check(manualBytes.subarray(0, 5).toString("ascii") === "%PDF-", "O arquivo baixado não é um PDF válido.");
check(manualBytes.byteLength > 500000, "O manual baixado parece incompleto.");

check(errors.length === 0, `Erros de console: ${errors.join(" | ")}`);
check(warnings.length === 0, `Avisos de console: ${warnings.join(" | ")}`);
check(externalRequests.length === 0, `Requisições externas detectadas: ${externalRequests.join(" | ")}`);
console.log(JSON.stringify({ ok: true, page: "index.html", localDatabase: true, planCopies: true, manualDownload: true, guidedSteps: 7, activitiesRequired: 2, eventDecisions: 2, explainedDimensions: 4, pointerSelection: true, directionButtons: true, zoomControls: true, rotationControl: true, keyboardFocus: true, viewports: [360, 768, 1024, 1440], consoleErrors: errors.length, consoleWarnings: warnings.length, externalRequests: externalRequests.length, screenshots: [join(qaDir, "journey-start-desktop.png"), join(qaDir, "composition-desktop.png"), join(qaDir, "composition-mobile.png"), join(qaDir, "layout-desktop.png"), join(qaDir, "layout-mobile.png"), join(qaDir, "review-desktop.png"), join(qaDir, "review-mobile.png"), join(qaDir, "manual-download-desktop.png"), join(qaDir, "manual-download-mobile.png")] }, null, 2));
await browser.close();
